addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"  % "1.8.1")
addSbtPlugin("com.geirsson"     % "sbt-scalafmt"         % "1.5.1")
addSbtPlugin("io.shiftleft"     % "sbt-ci-release-early" % "2.0.24")
addSbtPlugin("com.dwijnand"     % "sbt-dynver"           % "4.1.1")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "0.14.10")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"        % "0.8.0")
