addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"  % "1.3.5")
addSbtPlugin("com.geirsson"     % "sbt-scalafmt"         % "1.5.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"              % "1.0.0")
addSbtPlugin("io.shiftleft"     % "sbt-ci-release-early" % "1.2.2")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "0.14.5")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"        % "0.8.0")
