addSbtPlugin("com.github.sbt" % "sbt-native-packager"  % "1.9.8")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"         % "2.4.6")
addSbtPlugin("io.shiftleft"   % "sbt-ci-release-early" % "2.0.27")
addSbtPlugin("com.dwijnand"   % "sbt-dynver"           % "4.1.1")
addSbtPlugin("com.eed3si9n"   % "sbt-assembly"         % "1.1.0")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"        % "0.11.0")
