name: PR
on: pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15, macos-11]
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 1
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - name: Configure npm
        run: |
          npm set progress=false
          npm config set registry http://registry.npmjs.org/
      - name: Compile and run tests (1)
        if: ${{ matrix.os != 'windows-2019' }}
        run: |
          sbt +test
      - name: Compile and run tests (2)
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          & sbt +test
  formatting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.8
      - name: Check formatting
        run: sbt scalafmtCheck test:scalafmtCheck
      - run: echo "Previous step failed because code is not formatted. Run 'sbt scalafmt'"
        if: ${{ failure() }}
