name: PR
on: pull_request
env:
  POWERSHELL_TELEMETRY_OPTOUT: 1
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - name: Set up SBT
        uses: sbt/setup-sbt@v1
      - name: Compile and run tests
        run: sbt clean test
  formatting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - name: Check formatting
        run: sbt scalafmtCheck test:scalafmtCheck
      - run: echo "Previous step failed because code is not formatted. Run 'sbt scalafmt'"
        if: ${{ failure() }}
