name: PR
on: pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'sbt'
      - name: Compile and run tests
        run: sbt clean +test
  formatting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'sbt'
      - name: Check formatting
        run: sbt scalafmtCheck test:scalafmtCheck
      - run: echo "Previous step failed because code is not formatted. Run 'sbt scalafmt'"
        if: ${{ failure() }}
