name: PR
on: pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - name: Compile and run tests
        run: sbt -v -Dfile.encoding=UTF-8 "clean; +test;"
        shell: bash
  formatting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.8
      - name: Check formatting
        run: sbt scalafmtCheck test:scalafmtCheck
      - run: echo "Previous step failed because code is not formatted. Run 'sbt scalafmt'"
        if: ${{ failure() }}
